### ISSUE TITLE
Scrolling "marquee" text increases CPU fan

### ISSUE THREAD

**Issue by RalphCorderoy** [KaOSx/kaosx.github.io#3] opened 2017-01-16 12:40 UTC
Hi, heard of kaosx for the first time, visited https://kaosx.us/ in Firefox and my CPU fan increases in noise and power consumption rises.  Please consider axing those scrolling "marquee"-style texts.  They're distracting to try and read because they're moving.  When trying to read another part of the page they're distracting because there's movement which we're trained to be attracted to.

**Comment by vinzv** [comment] 2021-01-26 13:40
**On fan speed:**
I couldn't reproduce it on any of the machines I have access to. This disregarding how powerful or low-specced they were.

**On aesthetics:**
I'd not remove them because there's not much to read around the marquee texts which they could distract from.

As there has been no "+1" since four years I'd close this issue.

**Closed as completed** 2021-01-26 13:45 UTC

**Comment by RalphCorderoy** [comment] 2021-01-26 13:57
As you wish. I've just tried again and Firefox consumes an extra 40% on one CPU core when the marquee is visible, still causing the fan to speed up and make noise.
